language: rust
rust:
  - nightly

os:
  - linux
  - osx
  - windows

env: RELEASE=false

matrix:
  include:
  - os: linux
    env: BUILD_ANDROID=true RELEASE=false
# allow_failures:
# - env: BUILD_ANDROID=true RELEASE=false


before_install:
  - cargo install cargo-prune --force
  - if [ "$BUILD_ANDROID" == true ]; then
      ./install-ndk.sh;
      export NDK_HOME=`pwd`/NDK;
      ${NDK_HOME}/build/tools/make_standalone_toolchain.py --api 26 --arch arm64 --install-dir "${NDK_HOME}/arm64";
      ${NDK_HOME}/build/tools/make_standalone_toolchain.py --api 26 --arch arm --install-dir "${NDK_HOME}/arm";
      ${NDK_HOME}/build/tools/make_standalone_toolchain.py --api 26 --arch x86 --install-dir "${NDK_HOME}/x86";
      rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android;
    fi

install:
  - if [ "$BUILD_ANDROID" == true ]; then
        ./compile-android.sh;
    else
        cargo build --bin $($RELEASE && '--release');
        cargo build --lib $($RELEASE && '--release');
    fi

script:
  - cargo test --verbose $($RELEASE && '--release')


before_cache:
  - cargo prune

cache:
  cargo: true
