[package]
name = "aw_server"
version = "0.1.0"
authors = ["Johan Bjäreholt <johan@bjareho.lt>"]

[dependencies]
rocket = "0.3.16"
rocket_codegen = "0.3.16"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
chrono = { version = "0.4", features = ["serde"] }
rusqlite = { version = "0.14", features = ["chrono", "serde_json"] }
mpsc_requests = "0.2"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json"]
