name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
    - name: Cache cargo build
      uses: actions/cache@v1
      env:
        cache-name: cargo-build-target
      with:
        path: aw-server-rust/target
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-
    - name: Build
      run: cargo build --workspace --verbose
    - name: Run tests
      run: cargo test --workspace --verbose

  build-android:
    name: Build for Android
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
    - name: Cache cargo build
      uses: actions/cache@v1
      env:
        cache-name: cargo-build-target-android
      with:
        path: aw-server-rust/target
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-
    - name: Install NDK
      run: |
        ./install-ndk.sh
    - name: Build
      run: |
        export ANDROID_NDK_HOME=`pwd`/NDK
        ./compile-android.sh

  lint:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        components: clippy, rustfmt
        override: true
    - name: Check formatting  # Doesn't fail build
      run: cargo fmt -- --check || true
    - name: Run clippy  # Doesn't fail build
      run: cargo clippy
